services:
  database:
    image: postgres:15-alpine
    container_name: khoury-postgres
    ports:
      - "5433:5432"
    volumes:
      - khoury_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: khoury_computer_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  khoury_postgres_data: