spring:
  application:
    name: khoury-computer

  datasource:
    url: jdbc:postgresql://localhost:5433/khoury_computer_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB

app:
  upload:
    directory: uploads
    max-image-size: 5242880