spring:
  application:
    name: khoury-computer

  profiles:
    default: dev

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email

app:
  upload:
    directory: uploads
    max-image-size: 5242880