spring:
  application:
    name: khoury-computer

  profiles:
    default: dev

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB

app:
  upload:
    directory: uploads
    max-image-size: 5242880